import { toDDL, toDiff, qsql_version }                             from '../dist/quick-sql.js';
import { state, LS_ERD_POS, LS_ERD_COL }                          from './state.js';
import { highlightQuickSQL, highlightSQL }                          from './highlight.js';
import { capturePositions, updateDiagram, renderERD, applyErdTheme } from './erd.js';
import { init as initTabCallbacks, saveTabs, saveActiveTab,
         initTabs as loadTabs }                                      from './tabs.js';
import { init as initSettingCallbacks, initSettingsPanel }          from './settings.js';
import { init as initAcCallbacks, checkAutocomplete,
         handleKeydown as acKeydown, initAutocomplete }             from './autocomplete.js';

// ── DOM references ────────────────────────────────────────────────

const inputEl   = document.getElementById('input');
const qsHl      = document.getElementById('qs-hl');
const outputEl  = document.getElementById('output');
const errorEl   = document.getElementById('error');
const statusEl  = document.getElementById('status');
const lnEl      = document.getElementById('ln-layer');
const curLineEl = document.getElementById('cur-line');
const btnCopy        = document.getElementById('btn-copy');
const btnShare       = document.getElementById('btn-share');
const migWarningsEl  = document.getElementById('mig-warnings');

// ── Core update loop ──────────────────────────────────────────────

const DIFF_DELIMITER = /^#\s*-{2,}\s*$/m;

function makeFooter(input) {
    const safe = input.replace(/\/\*/g, '--<--').replace(/\*\//g, '-->--');
    return `\n-- Generated by Radicle QuickSQL ${qsql_version()} ${new Date().toLocaleString()}\n\n/*\n${safe}\n\n*/`;
}

function settingsSummary(src) {
    const m = /^#\s*settings\s*=\s*\{([^}]*)\}/im.exec(src);
    if (!m) return '';
    const body   = m[1];
    const get    = (key) => new RegExp(`\\b${key}\\s*[=:]\\s*["']?([^,}"'\\s]+)`, 'i').exec(body)?.[1];
    const parts  = [];
    const prefix = get('prefix');
    const db     = get('db');
    const pk     = get('pk');
    const api    = get('api');
    if (prefix && prefix !== 'null') parts.push(`prefix: ${prefix}`);
    if (db)                          parts.push(`db: ${db}`);
    if (pk)                          parts.push(`pk: ${pk}`);
    if (api)                         parts.push(`api: ${api}`);
    return parts.length ? '  ·  ' + parts.join('  ·  ') : '';
}

function updateCurLine() {
    if (!curLineEl) return;
    const s       = inputEl.selectionStart;
    const lineIdx = (inputEl.value.slice(0, s).match(/\n/g) || []).length;
    curLineEl.style.top = (14 + lineIdx * 13 * 1.65 - inputEl.scrollTop) + 'px';
}

// Flag set when typing while DDL tab is hidden — forces re-render on tab switch.
let ddlStale = false;

function renderDdl(ddl) {
    outputEl.innerHTML = highlightSQL(ddl) + '\n ';
    ddlStale = false;
}

function update() {
    const src   = inputEl.value;
    const lines = src.split('\n').length;
    lnEl.textContent = Array.from({ length: lines }, (_, i) => i + 1).join('\n');
    qsHl.innerHTML   = highlightQuickSQL(src) + '\n ';
    updateCurLine();

    const curTab = state.tabs.find(t => t.id === state.activeSchemaTabId);
    if (curTab) { curTab.qsql = src; saveTabs(); }

    const delimMatch = DIFF_DELIMITER.exec(src);

    try {
        let outputText;
        if (delimMatch) {
            const v1     = src.slice(0, delimMatch.index);
            const v2     = src.slice(delimMatch.index + delimMatch[0].length);
            const result = toDiff(v1, v2);
            outputText   = result.sql + makeFooter(src);
            const s      = result.summary;
            const manual = s.statementsRequiringIntervention;
            btnCopy.textContent  = '⧉ Copy Migration';
            statusEl.textContent = `Migration: +${s.tablesAdded} · ~${s.tablesModified} modified · ${s.statementsTotal} statements` +
                (manual ? ` · ⚠ ${manual} manual` : '') + settingsSummary(v2);
            statusEl.className = 'status-active';
            const warns = result.warnings;
            migWarningsEl.innerHTML = (warns.length > 0 ? '<div class="mig-warn-hdr">⚠ Migration notices</div>' : '') +
                warns.map(w => {
                    const cls = w.level === 'DESTRUCTIVE' ? 'mig-warn-destructive'
                              : w.level === 'LOSSY'        ? 'mig-warn-lossy'
                              :                              'mig-warn-info';
                    const loc = w.column ? `[${w.table}.${w.column}]` : `[${w.table}]`;
                    return `<div class="mig-warn ${cls}">&#9888; ${w.level}  ${loc}  ${w.message}</div>`;
                }).join('');
        } else {
            outputText           = toDDL(src);
            btnCopy.textContent  = '⧉ Copy';
            statusEl.textContent = `${outputText.split('\n').length} DDL lines generated${settingsSummary(src)}`;
            statusEl.className   = 'status-active';
            migWarningsEl.innerHTML = '';
        }
        state.lastDdlText     = outputText;
        errorEl.style.display = 'none';
        // Skip expensive highlight pass when DDL panel is not visible.
        if (state.activeTab === 'ddl') {
            renderDdl(outputText);
        } else {
            ddlStale = true;   // will be flushed on tab switch
        }
    } catch (e) {
        state.lastDdlText       = '';
        errorEl.textContent     = e.message || String(e);
        errorEl.style.display   = 'block';
        statusEl.textContent    = 'syntax error';
        statusEl.className      = 'status-error';
        btnCopy.textContent     = '⧉ Copy';
        migWarningsEl.innerHTML = '';
    }

    if (state.activeTab === 'erd') {
        if (state.erdDebounceTimer) clearTimeout(state.erdDebounceTimer);
        state.erdDebounceTimer = setTimeout(() => {
            capturePositions();
            state.erdDebounceTimer = null;
            updateDiagram(true);
        }, 350);
    }
}

// ── Theme toggle ──────────────────────────────────────────────────

(function initTheme() {
    const btn  = document.getElementById('btn-theme');
    const html = document.documentElement;

    function applyTheme(theme) {
        html.dataset.theme   = theme;
        btn.textContent      = theme === 'light' ? '🌙' : '☀';
        btn.title            = theme === 'light' ? 'Switch to dark theme' : 'Switch to light theme';
        btn.setAttribute('aria-pressed', theme === 'dark' ? 'true' : 'false');
        try { localStorage.setItem('qsql-theme', theme); } catch (_) {}
        applyErdTheme();
    }

    // Sync button label with the theme already applied by the inline <script>
    applyTheme(html.dataset.theme || 'dark');

    btn.addEventListener('click', () =>
        applyTheme(html.dataset.theme === 'light' ? 'dark' : 'light')
    );
})();

// ── Bootstrap ─────────────────────────────────────────────────────

initTabCallbacks({ update, capturePositions });
initSettingCallbacks({ update });
initAcCallbacks({ update });

loadTabs();   // parse URL hash / localStorage → state.tabs
update();     // initial render

const verEl = document.getElementById('app-version');
if (verEl) verEl.textContent = 'v' + qsql_version();

// ── Output tab switching ──────────────────────────────────────────

document.querySelectorAll('.tab-btn').forEach(btn => {
    btn.addEventListener('click', () => {
        const tab = btn.dataset.tab;
        if (tab === state.activeTab) return;
        if (state.activeTab === 'erd') capturePositions();
        saveActiveTab();
        state.activeTab = tab;
        document.querySelectorAll('.tab-btn').forEach(b => b.classList.toggle('active', b.dataset.tab === tab));
        document.querySelectorAll('.tab-pane').forEach(p => p.classList.toggle('active', p.dataset.tab === tab));
        if (tab === 'erd') requestAnimationFrame(() => updateDiagram(true));
        if (tab === 'ddl' && ddlStale && state.lastDdlText) renderDdl(state.lastDdlText);
    });
});

// ── Editor interaction ────────────────────────────────────────────

inputEl.addEventListener('scroll', () => {
    qsHl.scrollTop  = inputEl.scrollTop;
    qsHl.scrollLeft = inputEl.scrollLeft;
    lnEl.scrollTop  = inputEl.scrollTop;
    updateCurLine();
});

inputEl.addEventListener('keydown', (e) => {
    if (acKeydown(e)) return;   // autocomplete has priority when popup is open

    if (e.key === 'Tab') {
        e.preventDefault();
        const s = inputEl.selectionStart;
        const v = inputEl.value;
        inputEl.value = v.slice(0, s) + '   ' + v.slice(inputEl.selectionEnd);
        inputEl.selectionStart = inputEl.selectionEnd = s + 3;
        update();
    } else if (e.key === 'Enter') {
        e.preventDefault();
        const s         = inputEl.selectionStart;
        const v         = inputEl.value;
        const lineStart = v.lastIndexOf('\n', s - 1) + 1;
        const indent    = v.slice(lineStart, s).match(/^(\s*)/)[1];
        inputEl.value   = v.slice(0, s) + '\n' + indent + v.slice(inputEl.selectionEnd);
        inputEl.selectionStart = inputEl.selectionEnd = s + 1 + indent.length;
        update();
    }
});

inputEl.addEventListener('click',  updateCurLine);
inputEl.addEventListener('keyup',  updateCurLine);
inputEl.addEventListener('select', updateCurLine);
inputEl.addEventListener('input',  () => { update(); checkAutocomplete(); });

// ── Copy / Share / Download ───────────────────────────────────────

function flashBtn(btn) {
    btn.classList.add('ok');
    setTimeout(() => btn.classList.remove('ok'), 1400);
}

btnCopy.addEventListener('click', () => {
    if (!state.lastDdlText) return;
    navigator.clipboard.writeText(state.lastDdlText).then(() => {
        const prev = btnCopy.textContent;
        btnCopy.textContent = '✓ copied';
        flashBtn(btnCopy);
        setTimeout(() => { btnCopy.textContent = prev; }, 1400);
    });
});

btnShare.addEventListener('click', () => {
    if (state.activeTab === 'erd') capturePositions();
    let fragment;
    if (state.lastErdPos.size > 0 || state.collapsed.size > 0) {
        const data = { q: inputEl.value };
        if (state.lastErdPos.size > 0) data.p = [...state.lastErdPos.entries()];
        if (state.collapsed.size > 0)  data.c = [...state.collapsed];
        fragment = 'v2:' + encodeURIComponent(JSON.stringify(data));
    } else {
        fragment = encodeURIComponent(inputEl.value);
    }
    const url = window.location.href.split('#')[0] + '#' + fragment;
    navigator.clipboard.writeText(url).then(() => {
        const prev = btnShare.textContent;
        btnShare.textContent = '✓ link copied';
        flashBtn(btnShare);
        setTimeout(() => { btnShare.textContent = prev; }, 1400);
    });
});

document.getElementById('btn-download').addEventListener('click', () => {
    if (!state.lastDdlText) return;
    const blob     = new Blob([state.lastDdlText], { type: 'text/plain' });
    const a        = document.createElement('a');
    a.href         = URL.createObjectURL(blob);
    const ts       = new Date().toISOString().slice(0, 19).replace(/[T:]/g, '-');
    a.download     = DIFF_DELIMITER.test(inputEl.value) ? `migration-${ts}.sql` : `schema-${ts}.sql`;
    a.click();
    URL.revokeObjectURL(a.href);
});

document.getElementById('btn-compare').addEventListener('click', () => {
    if (DIFF_DELIMITER.test(inputEl.value)) return;
    inputEl.value += '\n\n# ---\n\n';
    inputEl.selectionStart = inputEl.selectionEnd = inputEl.value.length;
    inputEl.focus();
    update();
});

// ── Settings panel ────────────────────────────────────────────────

const settingsPanel = initSettingsPanel();

// ── Help drawer ───────────────────────────────────────────────────

const helpOverlay = document.getElementById('help-overlay');
const helpDrawer  = document.getElementById('help-drawer');

function openHelp()  { helpOverlay.classList.add('open');    helpDrawer.classList.add('open'); }
function closeHelp() { helpOverlay.classList.remove('open'); helpDrawer.classList.remove('open'); }

document.getElementById('btn-help').addEventListener('click', openHelp);
document.getElementById('help-close').addEventListener('click', closeHelp);
helpOverlay.addEventListener('click', closeHelp);

document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
        closeHelp();
        settingsPanel.classList.remove('open');
        document.getElementById('examples-panel').classList.remove('open');
    }
});

// ── Examples ─────────────────────────────────────────────────────

const EXAMPLES = [
    {
        label: 'Schema Migration (# ---)', desc: 'Incremental ALTER TABLE migration between two schema versions',
        qsql:
`employees
   name vc100 /nn
   email vc200
   department vc100

# ---

employees
   name vc100 /nn
   email vc200 /nn
   phone vc50

departments
   dept_name vc100 /nn
   employees
      name vc100 /nn
      email vc200 /nn
      phone vc50`,
    },
    {
        label: 'HR — Human Resources', desc: 'Departments, employees, jobs',
        qsql:
`departments /insert 3
   name /nn /upper
   location vc100
   budget num(12,2)
   employees /insert 10
      name /nn
      email /lower /nn
      hire_date date
      salary num(10,2)
      job_title vc100`,
    },
    {
        label: 'E-Commerce', desc: 'Customers, orders, products',
        qsql:
`customers /insert 5
   name /nn
   email /lower /nn /unique
   phone vc20
   orders /insert 3
      order_date date /nn
      status /check PENDING,SHIPPED,DELIVERED
      total num(10,2)
      order_lines /insert 4
         quantity int /nn
         unit_price num(10,2) /nn

products /insert 20
   name vc100 /nn /upper
   price num(10,2) /nn
   stock int
   category vc50`,
    },
    {
        label: 'Blog', desc: 'Authors, posts, comments',
        qsql:
`authors /insert 5
   name /nn
   email /lower /nn /unique
   bio
   posts /insert 8
      title vc200 /nn
      body clob
      published_at ts
      category /check TECH,NEWS,TUTORIAL
      comments /insert 3
         author_name /nn
         body vc2000 /nn
         posted_at ts`,
    },
    {
        label: 'Healthcare', desc: 'Doctors, patients, appointments',
        qsql:
`doctors /insert 8
   name /nn
   specialty vc100
   email /lower /nn /unique

patients /insert 20
   name /nn
   birth_date date
   phone vc20
   email /lower
   appointments /insert 15
      appointment_date ts /nn
      notes
      status /check SCHEDULED,COMPLETED,CANCELLED
      doctor_id /fk doctors`,
    },
    {
        label: 'Project Management', desc: 'Teams, projects, tasks',
        qsql:
`teams /insert 4
   name /nn
   budget num(12,2)
   projects /insert 6
      name vc100 /nn
      start_date date
      end_date date
      status /check PLANNING,ACTIVE,DONE
      tasks /insert 10
         title vc200 /nn
         due_date date
         priority /check LOW,MEDIUM,HIGH
         done bool`,
    },
    {
        label: 'Inventory', desc: 'Warehouses, categories, products',
        qsql:
`warehouses /insert 3
   name /nn
   location vc100
   categories /insert 5
      name /nn /upper
      description
      products /insert 20
         name vc100 /nn /upper
         sku vc50 /nn /unique
         price num(10,2) /nn
         quantity int /nn
         reorder_level int`,
    },
    {
        label: 'Star Schema', desc: 'Fact table with dimension tables (sales model)',
        qsql:
`sales /insert 10
   quantity int /nn
   amount   num(12,2) /nn
   > products /insert 5
      name     vc200 /nn
      category vc100
      price    num(10,2)
   > customers /insert 8
      full_name vc200 /nn
      country   vc2
      tier      /check STANDARD,GOLD,PLATINUM

# settings = { pk: identityDataType, semantics: CHAR }`,
    },
    {
        label: 'JSON Duality Views (23ai)', desc: 'Relational data exposed as JSON documents',
        qsql:
`departments
   name vc200 /nn
   employees
      first_name vc100 /nn
      last_name  vc100 /nn
      salary     num(10,2)

dv dept_emp_dv departments employees

# settings = { db: "23c", pk: identityDataType }`,
    },
    {
        label: 'Multi-lingual (/trans)', desc: 'Translated columns with _trans table and _resolved view',
        qsql:
`products
   name        vc200 /nn /trans
   description       /trans
   price       num(10,2) /nn

categories
   label vc100 /nn /trans

# settings = { prefix: "shop_", pk: identityDataType }`,
    },
    {
        label: 'Immutable + SODA + Vector', desc: 'Append-only ledger, document store, AI vector search',
        qsql:
`-- Immutable audit ledger (no UPDATE or DELETE allowed)
transactions /immutable /insert 5
   amount    num(14,2) /nn
   currency  vc3 /nn /default USD
   reference vc50 /nn /unique

-- SODA JSON document collection
sensor_readings /soda

-- Vector similarity search table (Oracle 23c+)
embeddings
   label      vc200 /nn
   content    clob
   embedding  vect1536

# settings = { db: "23c", pk: identityDataType }`,
    },
    {
        label: 'Oracle SQL Annotations', desc: 'DESCRIPTION, GROUP, custom key-value annotations',
        qsql:
`employees {DESCRIPTION 'HR workforce', Classification 'HR', GROUP 'PII'}
   full_name  vc200 /nn {DESCRIPTION 'Legal full name', Sensitivity 'Private'}
   email      vc200 /nn /unique /lower {DESCRIPTION 'Work email'}
   department vc100
   salary     num(12,2) {Sensitivity 'Confidential'}

# settings = { pk: identityDataType, auditcols: yes }`,
    },
    {
        label: 'Layered TAPI + Audit Log', desc: 'DAL / hooks / SVC + autonomous audit package',
        qsql:
`app_audit_log /api
   entity     vc128 /nn
   entity_id  num /nn
   operation  vc6 /nn
   old_values clob
   new_values clob

doctors /api /auditlog app_audit_log
   name      vc200 /nn
   specialty vc100
   email     vc200 /nn /unique

# settings = {"prefix": "a01_", "auditcols": "yes", "rowversion": "yes", "api": "layered", "apex": "yes"}`,
    },
    {
        label: 'Multi-Tenant SaaS', desc: 'Shared schema with tenant_id isolation',
        qsql:
`tenants /insert 2
  name      vc200 /nn
  plan_code /fk ref_subscription_plans /nn
  active    /check Y,N /nn /default Y

customers /insert 10
  tenant_id    num /nn /fk tenants
  full_name    vc200 /nn
  email        vc200 /nn /unique
  country_code vc3 /fk ref_countries

orders /insert 20
  tenant_id   num /nn /fk tenants
  customer_id num /nn /fk customers
  status      /check OPEN,SHIPPED,CLOSED,CANCELLED /nn /default OPEN
  total       num(14,2) /nn

order_lines /insert 50
  tenant_id  num /nn /fk tenants
  order_id   num /nn /fk orders
  sku        vc50 /nn
  qty        num /nn
  unit_price num(10,2) /nn

# settings = { prefix: "app", tenantid: no, auditcols: yes, rowversion: yes, drop: yes, db: "23c" }`,
    },
    {
        label: 'Multi-Tenant (auto)', desc: 'tenantid: yes — TENANT_ID, composite FK and auto-FK generated automatically',
        qsql:
`subscription_plans /notenantid    -- supra-tenant lookup: no TENANT_ID
  code  vc20 /nn /pk
  name  vc100 /nn
  price num(10,2) /nn

tenants /notenantid               -- master tenant table: supra-tenant
  name      vc200 /nn
  plan_code /fk subscription_plans /nn

customers                         -- TENANT_ID NOT NULL added automatically
  full_name   vc200 /nn
  email       vc200 /nn /unique   -- → (tenant_id, email) unique index
  plan_code   /fk subscription_plans  -- simple FK (supra-tenant target)

orders                            -- auto composite FK: (tenant_id, customer_id) → customers
  customer_id /fk customers /nn
  status      /check OPEN,SHIPPED,CLOSED /nn /default OPEN
  total       num(14,2) /nn

order_lines                       -- /cascade → ON DELETE CASCADE on composite FK
  order_id   /fk orders /nn /cascade
  sku        vc50 /nn
  qty        num /nn
  unit_price num(10,2) /nn

# settings = { prefix: "app_", tenantid: yes, auditcols: yes, drop: yes, db: "23c" }`,
    },
];

const examplesPanel = document.getElementById('examples-panel');
const btnExamples   = document.getElementById('btn-examples');

EXAMPLES.forEach((ex) => {
    const btn = document.createElement('button');
    btn.className = 'ex-item';
    btn.innerHTML = `<strong>${ex.label}</strong><span>${ex.desc}</span>`;
    btn.addEventListener('click', () => {
        inputEl.value = ex.qsql;
        examplesPanel.classList.remove('open');
        state.lastErdPos = new Map();
        state.collapsed.clear();
        state.lastRenderedInput = null;
        update();
    });
    examplesPanel.appendChild(btn);
});

btnExamples.addEventListener('click', (e) => {
    e.stopPropagation();
    settingsPanel.classList.remove('open');
    const isOpen = examplesPanel.classList.toggle('open');
    if (isOpen) {
        const r = btnExamples.getBoundingClientRect();
        examplesPanel.style.top  = r.bottom + 4 + 'px';
        examplesPanel.style.left = r.left + 'px';
    }
});

document.addEventListener('click', (e) => {
    if (!examplesPanel.contains(e.target) && e.target !== btnExamples)
        examplesPanel.classList.remove('open');
});

// ── ERD toolbar ───────────────────────────────────────────────────

document.getElementById('btn-erd-fit').addEventListener('click', () => {
    if (!state.x6graph) return;
    state.x6graph.zoomToFit({ padding: 40, maxScale: 1 });
    state.x6graph.centerContent();
});
document.getElementById('btn-erd-zin').addEventListener('click',  () => { if (state.x6graph) state.x6graph.zoom(0.15); });
document.getElementById('btn-erd-zout').addEventListener('click', () => { if (state.x6graph) state.x6graph.zoom(-0.15); });

document.getElementById('btn-erd-reset').addEventListener('click', () => {
    if (!state.lastErdData) return;
    state.lastErdPos = new Map();
    state.collapsed.clear();
    try { localStorage.removeItem(LS_ERD_POS); localStorage.removeItem(LS_ERD_COL); } catch (_) {}
    renderERD(state.lastErdData);
    saveActiveTab();
    saveTabs();
});

// ── Resize handle ─────────────────────────────────────────────────

(function initResize() {
    const handle    = document.getElementById('resize-handle');
    const panelsEl  = document.querySelector('.panels');
    const leftPanel = panelsEl.children[0];
    let dragging = false, startX = 0, startW = 0;

    handle.addEventListener('mousedown', (e) => {
        dragging = true; startX = e.clientX;
        startW   = leftPanel.getBoundingClientRect().width;
        handle.classList.add('dragging');
        document.body.style.cursor    = 'col-resize';
        document.body.style.userSelect = 'none';
        e.preventDefault();
    });
    document.addEventListener('mousemove', (e) => {
        if (!dragging) return;
        const total = panelsEl.getBoundingClientRect().width - 5;
        const newW  = Math.max(180, Math.min(total - 180, startW + e.clientX - startX));
        leftPanel.style.flex  = 'none';
        leftPanel.style.width = newW + 'px';
    });
    document.addEventListener('mouseup', () => {
        if (!dragging) return;
        dragging = false;
        handle.classList.remove('dragging');
        document.body.style.cursor    = '';
        document.body.style.userSelect = '';
    });
})();

// ── Autocomplete setup ────────────────────────────────────────────

initAutocomplete();

